# Generated by Django 3.1.3 on 2020-11-28 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed432f81-c120-4be4-992e-8418b873f649'), editable=False, primary_key=True, serialize=False),
        ),
    ]
